Repository readcrx-2/read.crx-2, pull requests merged in 2018-10, with the labels that each got.

#501 Update: まちBBSに書き込めるように+α
  src/manifest.json
  src/ui/VirtualNotch.ts
  src/view/config/_data.pug
  src/write/cs_write.coffee
  src/write/submit_res.coffee
  src/write/write.coffee
Labels: バグ, 機能追加

#503 Update: サブドメインなしのまちBBSに対応 close #502+α
  README.md
  src/background.coffee
  src/core/BBSMenu.coffee
  src/core/Board.coffee
  src/core/Thread.coffee
  src/core/URL.ts
  src/cs_addlink.coffee
Labels: バグ, 改善, 機能追加

#504 Fix: リファクタリング
  src/app/Callbacks.ts
  src/core/util.coffee
  src/write/submit_res.coffee
  src/write/submit_thread.coffee
  src/write/write.coffee
Labels: 改善

#505 Fix: 検索モードの保管タイミングを変更など
  src/view/search.coffee
  src/view/thread.coffee
Labels: バグ

#506 Update: ブックマークのインポートとエクスポートを可能にする & その他
  src/core/Bookmark.ts
  src/core/BookmarkEntryList.ts
  src/core/BrowserBookmarkEntryList.ts
  src/core/Notification.coffee
  src/core/ReadState.coffee
  src/core/util.coffee
  src/ui/Dialog.coffee
  src/view/board.coffee
  src/view/config.coffee
  src/view/config/_data.pug
  src/view/thread.coffee
  src/write/submit_thread.coffee
Labels: バグ, 機能追加

#508 Fix: NGが反映されないケースがある close #507
  src/view/config.coffee
Labels: バグ

#510 Update: jumppanelに最新50を追加
  src/view/config/_reload.pug
  src/view/thread.coffee
  src/view/thread.pug
Labels: 機能追加

#511 Fix: 書き込みタイムアウトのメッセージが表示されていなかった
  src/write/write.coffee
Labels: バグ
