Repository readcrx-2/read.crx-2, pull requests merged in 2018-07, with the labels that each got.

#442 Update: 板一覧からブックマークに追加/解除できるように+α refs #162
  src/core/BoardTitleSolver.coffee
  src/core/ThreadSearch.coffee
  src/core/util.coffee
  src/view/config.coffee
  src/view/config.pug
  src/view/config.scss
  src/view/search.coffee
  src/view/sidemenu.coffee
  src/view/sidemenu.pug
Labels: 改善, 機能追加

#443 Update: スレ内検索で正規表現を使用可能にする refs #125
  gulpfile.coffee
  src/common.scss
  src/image/svg/regexp.svg
  src/view/module.coffee
  src/view/thread.coffee
  src/view/thread.pug
Labels: 機能追加

#444 Fix: 正規表現マークが正しく表示されないのを修正
  src/image/svg/regexp.svg
  src/ui/TableSorter.coffee
  src/ui/ThreadList.coffee
Labels: バグ

#445 Update: ブックマークのソート順を保持できるように close #195+α
  src/app.ts
  src/view/bookmark.coffee
  src/view/config.pug
Labels: 改善, 機能追加

#446 Update: 全角記号なども検索の際そろえるように+α
  src/background.coffee
  src/core/Util.ts
  src/core/util.coffee
Labels: 改善

#448 Update: AAの縮小表示 refs #162+α
  src/app.ts
  src/core/Board.coffee
  src/core/ImageReplaceDat.coffee
  src/core/NG.coffee
  src/core/ReplaceStrTxt.coffee
  src/core/Thread.coffee
  src/ui/AANoOverflow.coffee
  src/ui/ThreadContent.coffee
  src/view/config.pug
  src/view/thread.coffee
  src/view/thread.scss
Labels: 改善, 機能追加

#449 Update: 設定のデザインを改善+α
  gulpfile.coffee
  package-lock.json
  package.json
  src/core/NG.coffee
  src/image/svg/regexp.svg
  src/ui/ThreadList.coffee
  src/view/config.coffee
  src/view/config.pug
  src/view/config.scss
  src/view/index.coffee
  src/view/module.coffee
  src/view/thread.coffee
  src/write/submit_thread.coffee
  src/write/write.coffee
Labels: 改善

#451 Fix: 副NGワードが効いていないのを修正
  package-lock.json
  package.json
  src/app.ts
  src/core/Cache.coffee
  src/core/NG.coffee
  src/core/Thread.coffee
  src/core/URL.ts
  src/cs_addlink.coffee
  src/shortQuery.d.ts
  src/ui/AANoOverflow.coffee
  src/ui/NextThreadSearch.ts
  src/ui/PopupView.coffee
  src/ui/SelectableAccordion.ts
  src/ui/Sortable.ts
  src/ui/Tab.ts
  src/ui/ThreadContent.coffee
  src/ui/ThreadList.coffee
  src/view/bookmark_source_selector.coffee
  src/view/index.coffee
  src/view/module.coffee
  src/view/thread.coffee
  src/write/cs_write.coffee
  src/write/submit_res.coffee
  src/write/write.coffee
Labels: バグ

#452 Update: 板一覧更新後に板名取得テーブルが更新されるように close #447
  src/core/BBSMenu.coffee
  src/core/BoardTitleSolver.coffee
  src/core/util.coffee
  src/view/sidemenu.coffee
Labels: バグ, 改善

#453 Fix: 「read.crx2で開く」が表示されないのを修正
  src/core/util.coffee
  src/cs_addlink.coffee
  src/ui/ThreadContent.coffee
Labels: バグ

#454 Fix: 新着の「何個目の書き込みか」がずれていたのを修正+α
  src/core/Bookmark.ChromeBookmarkEntryList.ts
  src/ui/Tab.ts
  src/ui/ThreadContent.coffee
  src/ui/ThreadList.coffee
  src/view/bookmark_source_selector.coffee
  src/view/config.coffee
  src/view/config.pug
  src/view/index.coffee
  src/view/inputurl.coffee
  src/view/module.coffee
  src/view/thread.coffee
  src/write/cs_write.coffee
  src/write/write.coffee
Labels: バグ, 改善, 機能追加
