Repository readcrx-2/read.crx-2, pull requests merged in 2018-09, with the labels that each got.

#471 Update: sassとpugも差分ビルドするように & Fix: #468がビルドできなかったのを修正
  gulp/config.coffee
  gulp/css.coffee
  gulp/html.coffee
  gulp/plugins.coffee
  gulp/watch.coffee
  package-lock.json
  package.json
Labels: バグ, 改善

#472 Fix: バグ修正 close #469
  src/background.coffee
  src/core/ContextMenus.coffee
  src/core/Thread.coffee
  src/core/URL.ts
  src/view/index.coffee
  src/view/module.coffee
  src/view/search.coffee
  src/view/sidemenu.coffee
Labels: バグ

#474 Fix: Firefoxでzoomが使えない件を修正 close #473
  src/ui/MediaContainer.coffee
Labels: バグ

#475 Fix: Firefoxで板一覧のアコーディオンを閉じたときのチラつきをなくす
  src/ui/Animate.coffee
Labels: バグ

#477 Fix: 非推奨/ブラウザ独自プロパティ/メソッドなどの除去
  src/core/util.coffee
  src/ui/ContextMenu.coffee
  src/ui/SelectableAccordion.ts
  src/ui/Sortable.ts
  src/ui/Tab.ts
  src/ui/ThreadList.coffee
  src/view/module.coffee
  src/view/sidemenu.coffee
  src/view/thread.coffee
Labels: バグ, 改善

#478 Fix: Firefoxのupdate_urlがjsonではなくxmlになっていたのを修正+α
  src/core/History.coffee
  src/core/WriteHistory.coffee
  src/manifest.json
Labels: バグ, 改善

#479 Fix: 板名の取得に失敗するのを修正+α
  src/_common.scss
  src/background.coffee
  src/core/BoardTitleSolver.coffee
  src/core/util.coffee
  src/ui/ThreadContent.coffee
Labels: バグ, 改善

#482 Fix: スレ検索で検索結果を開けないことがある
  src/view/index.coffee
Labels: バグ

#481 Fix: Firefoxでファビコンが表示されないのを修正 close #480+α
  gulp/config.coffee
  gulp/img.coffee
  gulp/js.coffee
  gulp/watch.coffee
  src/_base.pug
  src/manifest.json
  src/ui/ThreadContent.coffee
  src/view/index.coffee
  src/view/index.pug
  src/view/thread.scss
  src/write/_write.scss
  src/write/submit_res.pug
  src/write/submit_thread.pug
  src/write/submit_thread.scss
  src/write/write.coffee
  src/zombie.pug
Labels: バグ, 改善

#483 Fix: 既読情報が終了時に保存されていなかったのを修正+α
  src/app.ts
  src/background.coffee
  src/view/board.coffee
  src/view/config.coffee
  src/view/index.coffee
  src/view/thread.coffee
  src/zombie.coffee
  src/zombie.pug
Labels: バグ, 改善

#484 Fix: ブックマークを複数端末で共有している場合に未読数が正しく表示されていない + リファクタリング
  src/ui/ThreadContent.coffee
  src/view/thread.coffee
Labels: バグ

#486 Update: ホスト名付きサードレベルドメインの掲示板も読み込めるように+α
  src/core/Board.coffee
  src/core/NG.coffee
  src/core/Thread.coffee
  src/core/URL.ts
  src/ui/Tab.ts
  src/ui/ThreadContent.coffee
  src/ui/_Tab.scss
  src/view/config.coffee
  src/view/index.coffee
  src/view/thread.coffee
  src/view/thread.scss
Labels: バグ, 改善, 機能追加

#488 Update: NGレスによるぼかし判定を無視出来るようにする close #485
  src/ui/ThreadContent.coffee
Labels: 改善

#489 Fix: 最終既読位置がレスの頭に一致している場合に位置が正しく記録されていない
  src/ui/ThreadContent.coffee
  src/view/thread.coffee
Labels: バグ

#490 Fix: Vivaldiでは書き込みウィンドウをタブで開けるように
  src/view/board.coffee
  src/view/thread.coffee
  src/view/thread.scss
Labels: バグ

#491 Fix: read.crxを閉じたときウィンドウごと閉じられるのを修正+α
  gulp/config.coffee
  package-lock.json
  package.json
  src/zombie.coffee
Labels: バグ, 改善

#493 Fix: 検索結果/書込履歴のカラム省略がうまくいっていないのを修正 close #492+α
  src/_common.scss
  src/view/search.scss
  src/view/writehistory.scss
Labels: バグ, 改善

#494 Fix: Firefoxで設定や履歴のエクスポートができなかったのを修正
  src/_common.scss
  src/manifest.json
  src/view/config.coffee
Labels: バグ

#495 Update: クリックでサムネイルを読み込めるように+α refs #162
  src/_common.scss
  src/app.ts
  src/ui/LazyLoad.ts
  src/ui/MediaContainer.coffee
  src/view/config.pug
  src/view/module.coffee
  src/view/thread.coffee
Labels: 改善, 機能追加

#496 Fix: Vivaldiでzombieが閉じないことがあるのを修正
  src/zombie.coffee
Labels: バグ, ブラウザ:Vivaldi

#497 Fix: リファクタリング
  gulp/config.coffee
  gulp/html.coffee
  gulp/plugins.coffee
  gulp/watch.coffee
  package-lock.json
  package.json
  src/app.ts
  src/app/Callbacks.ts
  src/app/Config.ts
  src/app/Defer.ts
  src/app/Log.ts
  src/app/Message.ts
  src/app/Util.ts
  src/view/config.pug
  src/view/config/_data.pug
  src/view/config/_general.pug
  src/view/config/_info.pug
  src/view/config/_ng.pug
  src/view/config/_other.pug
  src/view/config/_popup.pug
  src/view/config/_reload.pug
  src/view/config/_thumbnail.pug
Labels: 改善

#498 Fix: リファクタリング
  src/core/Bookmark.ts
  src/core/BookmarkCompatibilityLayer.ts
  src/core/BrowserBookmarkEntryList.ts
  src/core/DOMData.coffee
  src/view/index.coffee
  src/zombie.coffee
Labels: 改善

#499 Update: 検索の追加読み込み中に"検索中"を表示するように
  src/_common.scss
  src/view/search.coffee
Labels: バグ, 改善

#500 Fix: リファクタリング
  src/core/Bookmark.ts
  src/core/BookmarkCompatibilityLayer.ts
  src/core/BookmarkEntryList.ts
  src/core/BrowserBookmarkEntryList.ts
  src/core/core.coffee
  src/view/bookmark.coffee
  src/view/index.coffee
  src/view/sidemenu.coffee
  src/zombie.coffee
Labels: バグ, 改善
